sudo: false
language: go

branches:
    only:
        - master

go:
    - 1.9

env:
    matrix:
        - GOOS=linux GOARCH=amd64
        - GOOS=darwin GOARCH=amd64
        - GOOS=windows GOARCH=amd64
        - GOOS=linux GOARCH=arm
        - GOOS=linux GOARCH=arm64

install:
#     - go get github.com/mattn/goveralls
    - go get -v -d -t
before_script:
    - go test ./... -v -cover
#     - goveralls -service=travis-ci
# # script:
#     # go install -v
# after_success:
#     - coveralls
