language: go

branches:
    only:
        - master

go:
    - 1.9.x
os:
    - osx

install:
    - go get -v -d -t
before_script:
    - go test ./... -v -cover
script:
    go install -v
deploy:
    true
