version: "2"
services:
    go:
        hostname: dnskek
        image: golang
        volumes:
            - .:/go/src/dnskek
        working_dir: /go/src/dnskek
        environment:
            # - GOBIN=/go/src/dnskek/dnskek
            - GOOS=darwin
            - GOARCH=amd64
        command: sh -c "go fmt ...; go-wrapper download; go build -v"
